name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check programs
      shell: bash
      run: |
        (which clang++ > /dev/null 2>&1) && echo "clang++ Yes" || echo "clang++ No"
        (which llvm-profdata > /dev/null 2>&1) && echo "llvm-profdata Yes" || echo "llvm-profdata No"
        (which llvm-cov > /dev/null 2>&1) && echo "llvm-cov Yes" || echo "llvm-cov No"
        (which lcov > /dev/null 2>&1) && echo "lcov Yes" || echo "lcov No"
        (which gcov > /dev/null 2>&1) && echo "gcov Yes" || echo "gcov No"

    - name: Setup python environment
      uses: actions/setup-python@v2
      env:
        cache-name: conan-pyenv
      with:
        python-version: 3.8
    - name: Install Conan
      run: |
        python -m pip install conan
        conan config init
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Cache conan packages
      uses: actions/cache@v2
      env:
        cache-name: conan-pkgs
      with:
        path: ~/.conan
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install C/C++ Dependencies
      working-directory: ${{runner.workspace}}/build
      #shell: bash
      run: |
        conan install $GITHUB_WORKSPACE
        cp $GITHUB_WORKSPACE/cmake/Find*.cmake ./

    - name: Setup project with cmake
      working-directory: ${{runner.workspace}}/build
      #shell: bash
      run: |
        cmake $GITHUB_WORKSPACE \
            -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DENABLE_CODE_COVERAGE=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE --verbose

    - name: Generate coverage data
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --target coverage-data

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{runner.workspace}}/build

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Save artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: ${{runner.workspace}}/build

    - name: Generate Profdata File
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: llvm-profdata merge -sparse -o default.profdata profraw/*.profraw

    - name: Show results of coverage report
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: llvm-cov report -instr-profile=default.profdata tests/*

    - name: Generate coverage as html
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: llvm-cov show -format=html -output-dir=html -instr-profile=default.profdata tests/*

    - name: Save report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ${{runner.workspace}}/build/html

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Save artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: ${{runner.workspace}}/build

    - name: Add execute perms
      working-directory: ${{runner.workspace}}/build
      run: chmod +x tests/*

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE


# vim: set sw=2 ts=2 expandtab:
